### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: totem_of_undying

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:totem_of_undying ~1 ~0 ~-0.375 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~1 ~0 ~-0.25 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~1 ~0 ~-0.125 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~1 ~0 ~0 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~1 ~0 ~0.125 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~1 ~0 ~0.25 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.875 ~0 ~-0.625 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.875 ~0 ~-0.5 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.875 ~0 ~0.375 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.875 ~0 ~0.5 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.75 ~0 ~-0.75 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.75 ~0 ~0.625 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.625 ~0 ~-0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.625 ~0 ~0.75 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.5 ~0 ~-0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.5 ~0 ~0.75 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.375 ~0 ~-1 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.375 ~0 ~0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.25 ~0 ~-1 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.25 ~0 ~0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.125 ~0 ~-1 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0.125 ~0 ~0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0 ~0 ~-1 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~0 ~0 ~0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.125 ~0 ~-1 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.125 ~0 ~0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.25 ~0 ~-1 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.25 ~0 ~0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.375 ~0 ~-0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.375 ~0 ~0.75 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.5 ~0 ~-0.875 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.5 ~0 ~0.75 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.625 ~0 ~-0.75 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.625 ~0 ~0.625 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.75 ~0 ~-0.625 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.75 ~0 ~-0.5 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.75 ~0 ~0.375 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.75 ~0 ~0.5 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.875 ~0 ~-0.375 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.875 ~0 ~-0.25 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.875 ~0 ~-0.125 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.875 ~0 ~0 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.875 ~0 ~0.125 0 1 0 1.4 0 normal @a
particle minecraft:totem_of_undying ~-0.875 ~0 ~0.25 0 1 0 1.4 0 normal @a
